language: objective-c
osx_image: xcode7.1
podfile: Example/Podfile
script:
    xctool 
    -workspace Example/MUKPullToRevealControl.xcworkspace 
    -scheme MUKPullToRevealControl 
    -sdk iphonesimulator
    build  
    CODE_SIGN_IDENTITY="" 
    CODE_SIGNING_REQUIRED=NO
notifications:
    email: false
